### ISSUE TITLE
Commits the node_modules directory in a  non-node project

### ISSUE THREAD

**Issue by irshsheik** [JossyDevers/transpiler-js#1]
### It does not have support for Class properties.

```js
SyntaxError: /github/workspace/assets/js/main.js: Support for the experimental syntax 'classProperties' isn't currently enabled (2:27):

  1 | class  Theme{
> 2 |     hasMenuOpacityEnabled = false;
    |                           ^
  3 |     hoveredIn = false;
  4 | 
  5 |     LIGHT_LIGHT = "light_light_theme";
```

There is already a fix around on stackoverflow - [Link here](https://stackoverflow.com/questions/52237855/support-for-the-experimental-syntax-classproperties-isnt-currently-enabled).

**Comment by JossyDevers** [comment]
Hey @igagrock, thanks for reporting this error, I did the fix for it and published the v1.0.1 version of the pipeline.

Anything you notice or modifications you want can create another issue.
